### ISSUE TITLE
[Bug] False positive in Special Edition

### ISSUE THREAD

**Issue by mynameisbogdan** [TRaSH-Guides/Guides#1089]
**Which Guide**
Radarr: Special Edition

**Describe the Error in the Guide**
`The.Final.Cut.2004.1080p.AMZ.WEB-DL.DD+5.1.x264-NOGROUP` gets a false positive on `Special Edition`

**Expected behavior**
Not to be labeled as `Special Edition` since `The Final Cut` it's the name of the movie.

**Screenshots**
![Screenshot 2023-01-12 at 04 46 28](https://user-images.githubusercontent.com/707714/211963851-1e24acc2-8277-472b-a73d-b3f13702ce65.jpg)

**Comment by bakerboy448** [comment]
Not a guide issue.

https://github.com/Radarr/Radarr/issues/7004
