### ISSUE TITLE
[Bug] A file containing both HDR10+ and DV profiles is incorrectly matched

### ISSUE THREAD

**Issue by AN1MATEK** [TRaSH-Guides/Guides#1285]
**Which Guide**
HDR10+ profile within the Radarr guide

**Describe the Error in the Guide**
The following file contains both DV and HDR10+, but the matching shows only [DV] and [Hybrid]
```
mediainfo Ant-Man.and.the.Wasp.Quantumania.2023.German.EAC3D.DL.2160p.Hybrid.WEB.DV.HDR10Plus.HEVC-QfG.mkv
...
HDR format: Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile A compatible
...
```
**Expected behavior**
The file should also match [HDR10+] and [HDR10+ Boost] and therefore be downloaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/15142596/234547021-dbf10663-994e-4d43-8768-cd1a672316ec.png)

**Comment by TRaSH-** [comment]
It's easier to discuss this in discord.
But the cf matching works like how Radarr handles it.
DV HDR10Plus doesn't officially exist
So HDR10Plus cf shouldn't match
But I can take a look at the HDR10Plus booster to match these non official existing combination.

**Comment by facundo59** [comment]
Sorry I am not quite sure how to use Discord. 

It seems that this movie is an hybrid file including both profiles, I haven't tried to play this on my AppleTV so far. I am curious what profile will be used. Will do when I get home. 

Can I provide you with any more information/help? I would be happy to do so.

**Comment by facundo59** [comment]
I do use Recyclarr for the syncing. I don't even pretend I would change something in your holy guides.

The filter for [DV HDR10] specifically rejects the match if there is a "+" at the end. But here it actually says "Plus", so I don't know.

**Comment by TRaSH-** [comment]
Correct the custom formats follows the official formats, the same that Radarr uses
Being that Radarr after import won't rename it to DV HDR10+ but to DV HDR10

**Comment by nuxencs** [comment]
> It's easier to discuss this in discord. But the cf matching works like how Radarr handles it. DV HDR10Plus doesn't officially exist So HDR10Plus cf shouldn't match But I can take a look at the HDR10Plus booster to match these non official existing combination.

I'm 90% sure that changing the HDR10Plus booster CF to match that, will result in download loops:

`DV` + `HDR10Plus` on download -> `1500` + `901` = `2401`
`DV HDR10` on import -> `1500`

**Comment by TRaSH-** [comment]
ahh true that's why we never added it, couldn't remember it, and it isn't really needed if you follow the guide scores.

**Comment by AN1MATEK** [comment]
Hello there,

I would like to reopen this issue, given that Radarr just added support for this hybrid format in [#9457](https://github.com/Radarr/Radarr/pull/9457). 

BR
