### ISSUE TITLE
[REQUEST] DiscoFlix Integration

### ISSUE THREAD

**Issue by nickheyer** [TRaSH-Guides/Guides#1345]
**For which application would like to see this Guide ?**

[DiscoFlix](https://github.com/nickheyer/DiscoFlix) - An easy to setup Discord request bot and web ui for handling Radarr/Sonarr requests. Includes a REST API for scalability and open development.

**Describe what you would like to see in the Tutorial/Guide**

I noticed that you did not include any Discord-interfacing applications to facilitate user requests. If at any point you are open to it, I would be happy to create some easy to follow documentation that you could include wherever you'd see fit. I would make sure to follow the same style you have implemented in your other docs.

This documentation could include an install guide (for docker based installation & building from source), a guide to generating a Discord Bot API Token, API endpoints, etc. Open to your suggestions.

I can create a PR and edit the docs myself, or I can send you documentation that you could integrate, or you could create your own based on what currently exists in the [DiscoFlix Github](https://github.com/nickheyer/DiscoFlix). I'm open to whatever works for you.

**Why it would be a good fit**

I may be biased as it's creator, but I think DiscoFlix is a top contender when it comes to Radarr & Sonarr requests via Discord. It's easy to setup with Docker or even build from source. It has a clean user interface. It has been and will continue to be consistently maintained/improved. 

I am monitoring for all relevant updates to the Radarr / Sonarr API as well as Discord's Bot API. If something breaks, it will be immediately addressed. Other similar utilities might not be able to say the same.

If you'd require DiscoFlix to meet a specific criteria that it currently does not, please let me know and I will do my best to accommodate that. If you simply do not want to include this information in your docs, I'd understand. Either way, I appreciate you putting this together!

**Comment by TRaSH-** [comment]
I try to cover in the guide stuff I use myself, being it's much easier to maintain and give support about apps you actually use.

One of the reasons why I don't have a Lidarr guide, and I had several people who wanted to do it and maintain it.
Only one person actually showed me a setup he wanted to use and that was also the things I heard about it.

Or something I'm using notifiarr to sync my custom formats from the guide and more from the guide.
And I use it also for notifications, but I don't use any of the other options it supports like discord request for the Starr apps like yours.
The app has its own wiki that covers everything, so there was no need for me to maintain the guide here and I dropper it.

Looking fast at your readme it seems you already have most of it covered if not all
Only thing what I'm missing is a docker compose example.
If you have a proper readme/wiki there is no need for a 3rd party guide
