### ISSUE TITLE
[Bug] Renaming format for emby: Changed - to =

### ISSUE THREAD

**Issue by Amateur-God** [TRaSH-Guides/Guides#1371]
**Which Guide**
Renaming format for emby

**Describe the Error in the Guide**
the current naming format for emby isnt great as emby now uses tvdib={id}, imdbid={id} and tmdbid={id} to identify shows with the dbid in the name the current format says to name them with tvdbid-{id} which is the old formatting.

**Additional context**
i had some issues with emby misidentifying tvshows when i followed the naming convention in the guides and i asked on the emby forums for help, where it was pointed out that emby isnt recognising the dbids in the names as they arent labeled in a way that emby recognises them and i was told the correct way to label them, i have since been testing this change to the naming format for a couple monts now and ive had no further issues with it mis-identifying shows or episodes

TV
Standard episode format
{Episode CleanTitle} - S{season:00}E{episode:00} - [tvdbid={TvdbId}] [imdbid={ImdbId}] - [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRange]}[{MediaInfo VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo AudioLanguages}{-Release Group}

Anime Episode Format
{Episode CleanTitle} S{season:00}E{episode:00} - {absolute:000} - [tvdbid={TvdbId}] [imdbid={ImdbId}] - [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRange]}[{MediaInfo VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo AudioLanguages}{-Release Group}

Series Folder Format
{Series CleanTitle} ({Series Year}) [tvdbid={TvdbId}] [imdbid={ImdbId}]

Movies
Standard Movie Format
{Movie CleanTitle} {(Release Year)} [imdbid={ImdbId}] [tmdbid={TmdbId}]- {Edition Tags }{[Custom Formats]}{[Quality Full]}{[MediaInfo 3D]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels}]{MediaInfo AudioLanguages}[{MediaInfo VideoBitDepth}bit][{Mediainfo VideoCodec}]{-Release Group}

Movie Folder Format
{Movie CleanTitle} ({Release Year}) [imdbid={ImdbId}] [tmdbid={TmdbId}]

https://emby.media/community/index.php?/topic/118056-incorrect-identity-tv-shows/

https://emby.media/support/articles/Movie-Naming.html

**Comment by bakerboy448** [comment]
`tvdib` is arguably a bug with emby given there is nothing called `tvd` and it doesnt follow any formats or standards literally everyone but them use.

**Comment by bakerboy448** [comment]
Closing; Non-issue - user error.

Your naming schema is incorrect and doesn't follow the guide.
The guide is accurate.

Guide: `{Series TitleYear} [tvdbid-{TvdbId}]`
[Emby Post](https://emby.media/community/index.php?/topic/118056-incorrect-identity-tv-shows/&do=findComment&comment=1245760): `tvdbid`
[Emby Docs](https://emby.media/support/articles/Movie-Naming.html#id-tags-in-folder--file-names): `tvdbid`

**Comment by Amateur-God** [comment]
> ~Closing; Non-issue - user error.~
> 
> ~Your naming schema is incorrect and doesn't follow the guide.~ ~The guide is accurate.~
> 
> [Guide](https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/#optional-series-folder-format-for-the-plex-tv-series-scanner-and-jellyfinemby): `{Series TitleYear} [tvdbid-{TvdbId}]` [Emby Post](https://emby.media/community/index.php?/topic/118056-incorrect-identity-tv-shows/&do=findComment&comment=1245760): `tvdbid` [Emby Docs](https://emby.media/support/articles/Movie-Naming.html#id-tags-in-folder--file-names): `tvdbid`
> 
> Edit to reopen - ah I see it.
> 
> The OP details are mostly wrong and your naming on the linked post is wrong and doesn't match the guide. But it seems possible that Emby changed to requiring `SOURCE=ID` from `SOURCE-ID`
> 
> @Amateur-God please confirm with Emby that `{Series TitleYear} [tvdbid-{TvdbId}]` no longer works and Emby now requires `{Series TitleYear} [tvdbid={TvdbId}]`..... based on the linked thread and your GHI OP there's no evidence to suggest that `-` is no longer supported. The linked thread did not match the guide at all and `tvdb-{TvdbId}` as used by the thread's OP is not what the guide said to use.

Yes emby now requires = instead of -, I have discussed this with trash in the discord, they asked me to open this issues so that they remember to change it

the evidence of this can be found in both the forum and emby guide that I linked, here is a screenshot taken from the guide where it is mentioned that tmdbid, tvdbid etc require ``=``

My naming doesn't match the trash guide because these are suggestions of updated naming conventions for emby that I've tested and confirmed working with emby.

![image](https://github.com/TRaSH-/Guides/assets/68581288/9b8031cf-2e54-4f73-8652-97db6771953b)

**Comment by TRaSH-** [comment]
did someone find out when they decided to change this ?

**Comment by Amateur-God** [comment]
> did someone find out when they decided to change this ?

At the very least its been since march/april as that's when I noticed the issues I was having and questioned it on the emby forum, not sure of an exact date however could of been longer than that

**Comment by TRaSH-** [comment]
this should be something that should show up in the changelog, but i can't find it, also i can't do a search on the forum, to see if i can find somewhere the old recommendation

**Comment by Amateur-God** [comment]
> this should be something that should show up in the changelog, but i can't find it, also i can't do a search on the forum, to see if i can find somewhere the old recommendation

ill ask them on the forum when it changed

**Comment by bakerboy448** [comment]
they've claimed that `-` was *never* supported....

`there was never a change. i don't recall ever supporting it with a dash. It's easy enough to add, but I'm pretty sure we've never done it before.`
https://emby.media/community/index.php?/topic/118056-incorrect-identity-tv-shows/&do=findComment&comment=1261482
