### ISSUE TITLE
[Bug] EZTV regex in retags CF not complete

### ISSUE THREAD

**Issue by charmbv** [TRaSH-Guides/Guides#1423]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [X] Sonarr
- [ ] Other

### Description

Some torrent sites show EZTV releases with an addional suffix, e.g.

    The Witcher S03E03 1080p WEB h264-ETHEL[eztv re] mkv

I would like to update the following files to include the suffix in the regex if that is OK:

- `./docs/Sonarr/Sonarr-Release-Profile-RegEx.md`
- `./docs/Downloaders/SABnzbd/scripts/Clean/Clean.py`
- `./docs/Downloaders/NZBGet/scripts/Clean/Clean.py`
- `./docs/json/sonarr/rp/optionals.json`
- `./docs/json/sonarr/cf/retags.json`
- `./docs/json/sonarr/cf/french-lq.json`
- `./docs/json/radarr/cf/retags.json`
- `./docs/json/radarr/cf/french-lq.json`

### Expected Behavior

Also match `[eztv re]` as a retagged release.

**Comment by TRaSH-** [comment]
If you want to make the changes and create a pull request we will review it and help if needed to accomplish it.
