### ISSUE TITLE
[Bug] Add VXT to LQ CFs

### ISSUE THREAD

**Issue by kdbruin** [TRaSH-Guides/Guides#1426]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [X] Sonarr
- [ ] Other

### Description

As far as I can recall `VXT` was used for foreign releases on the old rarbg torrent site. So I think it should also be added to the LQ CFs just as `RARBG` is.

### Expected Behavior

Score `VXT` the same way as `RARBG` releases.

**Comment by TRaSH-** [comment]
Do you have a few release name examples?

**Comment by kdbruin** [comment]
For example:

    Faithfully Yours 2022 DUTCH 1080p WEBRip x264-VXT

**Comment by kdbruin** [comment]
But I think it only relates to Radarr and not Sonarr. That's because I don't see `RARBG` mentioned in the `lq.json`.

**Comment by TRaSH-** [comment]
Well I'm not sure if we should add foreign releases to lq
They clearly mention it's Dutch (probably Dutch subs or a second audio track)
As long as they don't add the foreign audio track as main.
Because then they go in to another CF

**Comment by kdbruin** [comment]
No problem, I will create a separate LQ custom format locally.

**Comment by TRaSH-** [comment]
It would be ignored anyway if you setup a language profile
