### ISSUE TITLE
[Bug] SABnzbd - Post processing has no "Use tags from indexers" settings

### ISSUE THREAD

**Issue by NLZ** [TRaSH-Guides/Guides#1452]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [X] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [ ] Radarr
- [ ] Sonarr
- [ ] Other

### Description

SABnzbd Settings => Switches => Post processing no longer contains "Use tags from indexers":
https://github.com/TRaSH-Guides/Guides/blob/1875b91fdaf19a0ae9dd06685207f3f77fdfb99f/docs/Downloaders/SABnzbd/Basic-Setup.md?plain=1#L97

Not sure when it was changed, but it's not in 4.0.3

### Expected Behavior

Remove the line and update the screenshot, maybe update where it was moved (if it was moved and not removed, I can't find it)

### Screenshots

![image](https://github.com/TRaSH-Guides/Guides/assets/884277/50fb1d59-bd5d-47d2-8458-5aa2f6250588)

**Comment by MaienM** [comment]
Looks like it was removed in 3.7.0Alpha1 ([release notes](https://github.com/sabnzbd/sabnzbd/releases/tag/3.7.0Alpha1), [commit removing it](https://github.com/sabnzbd/sabnzbd/commit/b3206fe1db8e1d7af6fe26069cac4a7783a290f9)) and is now just always enabled, so just removing it from the guide should be sufficient.
