### ISSUE TITLE
[Bug] TrueNAS Core NFSv4 owner and group is nobody unless using NFSv3 compatability

### ISSUE THREAD

**Issue by zilpe** [TRaSH-Guides/Guides#1476]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [X] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [ ] Radarr
- [ ] Sonarr
- [ ] Other

### Description

Hi,

If the NFSv4 option is selected in the [Configure and enable NFS service](https://trash-guides.info/Hardlinks/How-to-setup-for/TrueNAS-Core/#configure-and-enable-nfs-service) section of the guide, then the GID and UID reported by the client after running `ls l` will be `nobody 4294967294`.

This is an issue due to idmapping being incorrectly done in NFSv4, as explained in detail [here](https://www.suse.com/support/kb/doc/?id=000017244), even if all the steps are followed exactly.

The simple solution is to recommend users to tick the 'NFSv3 ownership model for NFSv4' box as well, since this issue does not occur with that setting enabled and the correct UID:GID is shown. 

Thanks for the great resource!

### Expected Behavior

The correct UID:GID should be shown as configured in TrueNAS, not 'nobody:4294967294'

**Comment by datcactus** [comment]
I'll update the documentation to be a bit more verbose about this. I mention the `nobody` issue in the group section, but not the user section and I don't cover idmapping explicitly. My clients are part of the same domain and have idmapping properly configured so I don't run into this issue, but I can see how others might.

**Comment by zilpe** [comment]
Thanks, @datcactus!

In the SUSE article linked, they say this:

> When NFS 4.x was original conceived and implemented, a feature of ID mapping was created and mandated.  This concept had weaknesses both foreseen and unforeseen, so it has since become undesired and optional. 

This is the general consensus I've seen online too. It would be a good idea to mention both options of editing the idmapping or ticking the NFSv3 compatability option. Thanks again for your efforts!

**Comment by bakerboy448** [comment]
@datcactus friendly reminder
