### ISSUE TITLE
[Bug] update notifiarr flowcharts

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-Guides/Guides#1496]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [ ] Radarr
- [ ] Sonarr
- [X] Other

### Description

Notifiarr interactive flow charts require updating

### Expected Behavior

Update flowcharts and details

### Additional Context

Make these accessible to the team for updates

**Comment by bakerboy448** [comment]
- [ ] provide @austinwbest updated images

**Comment by bakerboy448** [comment]
- [x] Sonarr
- [ ] Radarr
- [ ] Radarr SQP 1
- [ ] Radarr SQP 2
- [ ] Radarr SQP 3
- [ ] Radarr SQP 4
- [ ] Radarr SQP 5

**Comment by bakerboy448** [comment]
@TRaSH- whats remaining for this?

**Comment by TRaSH-** [comment]
everything should be updated
