### ISSUE TITLE
Add Default/Legacy Score for Streaming Services

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-Guides/Guides#1502]
most of the streaming services also don't have a default/legacy score and because of that these are hardcoded

_Originally posted by @nuxencs in https://github.com/TRaSH-Guides/Guides/pull/1463#discussion_r1293847438_

**Comment by nuxencs** [comment]
need to be agreed on with @austinwbest and @rcdailey because an explicit score of 0 would cause sync loops with notifiarr. don't know if that changed since then, was about 1 year ago 😅

**Comment by rcdailey** [comment]
Can someone explain what a "default/legacy" score is? I don't have a lot of context / explanation to go on.

Is the question for me if a `trash_score` of `0` is going to cause issues in Recyclarr?

**Comment by bakerboy448** [comment]
Legacy is `trash_score` default is `trash_scores.default` or whatever the syntax is

**Comment by nuxencs** [comment]
> Is the question for me if a `trash_score` of `0` is going to cause issues in Recyclarr?

I know that that was an issue with notifiarr before, that's why `trash_score: 0` doesn't exist in the jsons. just wanted to make sure if it was just an issue with notifiarr and not recyclarr as well

**Comment by austinwbest** [comment]
There has not been a 0 score for a reason for years. There is no need other than someone "wanting" it needed now. The sync has worked as is for years in both apps.
