### ISSUE TITLE
Bug in naming convention of Standard Movie Format

### ISSUE THREAD

**Issue by Zxurian** [TRaSH-Guides/Guides#1540]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [ ] Sonarr
- [ ] Other

### Description

The guide at https://trash-guides.info/Radarr/Radarr-recommended-naming-scheme/ shows the Standard Movie Format as `{Movie CleanTitle} {(Release Year)} {imdb-{ImdbId}} {edition-{Edition Tags}} {[Custom Formats]}{[Quality Full]}{[MediaInfo 3D]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels}][{Mediainfo VideoCodec}]{-Release Group}` however there's a mismatch in nesting brackets.

The MediaInfo section specifically is`{[Mediainfo AudioCodec}{ Mediainfo AudioChannels}]`. I don't know what was intended but the square/curly braces are transposed at either end resulting in a nesting mismatch. It doesn't appear to affect naming convention, as every video file has an audio codec & channels, but for naming accuracy should be corrected.

### Expected Behavior

Should be either
`[{Mediainfo AudioCodec}{ Mediainfo AudioChannels}]` or `{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}` depending on what was desired. I'm thinking the former, since `AudioCodec` and `AudioChannels` will be present on every video file, and will match the VideoCodec convention.

**Comment by TRaSH-** [comment]
Radarr: `{[Mediainfo AudioCodec}{ Mediainfo AudioChannels}]`
Sonarr: `{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}`

So it looks like the Radarr one has a copy/paste error
the reason why the curly brackets are at the end is for movies without audio, some very old movies
