### ISSUE TITLE
[Bug] Outdated screen

### ISSUE THREAD

**Issue by yoobi** [TRaSH-Guides/Guides#1570]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [X] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [ ] Radarr
- [ ] Sonarr
- [ ] Other

### Description

When following guide from the unraid section to setup folders, the screen is outdated

### Expected Behavior

Make a new screen with latest version of unraid

### Screenshots

![outdated](https://trash-guides.info/Hardlinks/How-to-setup-for/images/unraid-main-share.png)

----

<img width="1296" alt="Screenshot 2023-09-25 at 10 55 39" src="https://github.com/TRaSH-Guides/Guides/assets/17434735/0a7d23a9-eeb9-480d-a37d-d66836e680ef">

**Comment by TRaSH-** [comment]
I can't provide a new screenshot myself at that moment, being I'm still on 6.11.5 and haven't found the time to upgrade.

**Comment by yoobi** [comment]
The second screenshot in the issue is the config of 6.12+ which is equivalent to the one prior 6.12

**Comment by zakkarry** [comment]
After adding tabs in the mover page of deluge, we could also offer Unraid 6.11 and 6.12 tabs with the images I think.

This might be a good way to maintain the backwards compatibility for the guide, I believe most - if not all - of the fields that should be edited are almost identical in naming, so the guide itself shouldn't need much if any changes.

Something like this should be good.

https://dox.ary.dev/Hardlinks/How-to-setup-for/Unraid/#preparation
