### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by jakej1020** [TRaSH-Guides/Guides#1596]
### For which application would like to see this Guide?

Sonarr

### Describe what you would like to see in the Guide

I would like to see an optional setting added for preferring Dolby Atmos (such as what is provided by Netflix or in blu-ray rips).

**Comment by bakerboy448** [comment]
There's no need for this.  The sonarr guide (both v4 linked below and V3) already only targets webdls which will almost never have Atmos.  As the guide notes if you want advanced audio formats - target remuxes

https://trash-guides.info/Sonarr/sonarr-setup-quality-profiles/

**Comment by jakej1020** [comment]
@bakerboy448 That makes sense for the remix portion, but from what I can see a lot of Netflix original content has Atmos support.  Is there something I am misunderstanding?
