### ISSUE TITLE
[Bug] CF for x265 does not include HEVC

### ISSUE THREAD

**Issue by gjobin** [TRaSH-Guides/Guides#1600]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [X] Sonarr
- [ ] Other

### Description

Comparing the x265 related CF's, the basic one does not properly include "HEVC" like the other do.
<img width="956" alt="image" src="https://github.com/TRaSH-Guides/Guides/assets/9118970/4050e5e9-c189-42ff-a2f1-108f39e6bd80">

Thank you.

### Expected Behavior

HEVC should match x265 custom format.

### Additional Context

Applies to both Sonarr and Radarr

**Comment by bakerboy448** [comment]
Condition Naming issue only; not a material bug

the CF still includes hevc

"[xh][ ._-]?265|\\bHEVC(\\b|\\d)"

**Comment by gjobin** [comment]
> Condition Naming issue only; not a material bug
> 
> the CF still includes hevc
> 
> "[xh][ ._-]?265|\bHEVC(\b|\d)"

That is interesting, cause the CF label did not show on a movie containing HEVC. 
There definitely are cases where it does not seem to work as expected, but would like to understand if I am mistaken.
You're right though, labeling does'nt matter, and did not check down to the Regex.

Working Case : 
<img width="1607" alt="image" src="https://github.com/TRaSH-Guides/Guides/assets/9118970/3fbaebf2-3c0d-4bbe-8d34-744b6291d728">

Seemingly incorrect case :
<img width="1593" alt="image" src="https://github.com/TRaSH-Guides/Guides/assets/9118970/90ecc664-e823-4495-b17b-c195df9998bc">

**Comment by gjobin** [comment]
Makes sense. Sorry I did not catch that.
