### ISSUE TITLE
[Bug] Remux-2160p Books?

### ISSUE THREAD

**Issue by Aaron-Collis** [TRaSH-Guides/Guides#1602]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [ ] Sonarr
- [ ] Other

### Description

quality-definitions are just wrong. Remux books? I don't think so.

### Expected Behavior

Should have 
![image](https://github.com/TRaSH-Guides/Guides/assets/20622475/c0839441-1837-4a7c-8e3b-9e74c8d3bcb7)

### Screenshots

https://trash-guides.info/Radarr/Radarr-Quality-Settings-File-Size/#radarr-quality-definitions

**Comment by TRaSH-** [comment]
No books in Radarr
