### ISSUE TITLE
[Request] (Radarr): Add `PTer`, `Dkore` & `DiscoD` to UHD Bluray Tier 03

### ISSUE THREAD

**Issue by AutoGitr** [TRaSH-Guides/Guides#1612]
### For which application would like to see this Guide?

Radarr

### Describe what you would like to see in the Guide

The UHD releases of these three groups match or surpass the quality of BHDStudio releases, which is now in UHD Bluray Tier 03.

**Comment by TRaSH-** [comment]
PTer => will do some more research because i find mainly foreign stuff and movies that are 20-50 years old
Dkore => won't add they only have a handful of releases and only a few movies that are 20 years + old
DiscoD => isn't a rlsgrp but a uploader/encoder and will be picked up as hone because if their weird naming scheme.

**Comment by TRaSH-** [comment]
> The UHD releases of these three groups match or surpass the quality of BHDStudio releases, which is now in UHD Bluray Tier 03.

The others 2 were one of them isn't even a RlsGrp, will be denied with the reasons above.
Then we have only PTer left, my first findings. 
- Foreign Stuff
- Niche stuff
- Do you have actually have another reason why PTer should be added ?

**Comment by AutoGitr** [comment]
> > Yes, DiscoD will be picked up as HONE so no need to add it.
> 
> Before making suggestions for a rlsgrp make sure you do research Like suggest a rlsgrp that isn't a release group in the first case but a encoder!
> 
Yep, we are in agreement. Let's try to move on.
> > Firstly, what need is there for a reason to add them when the groups match the criteria stated on the website? Criteria from https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#hq-release-groups:
> > 
> > * Groups that created encodes from the remuxes without micro-sizing them.
> > * HDR/DoVi (Depending what's offered and often both)
> > * HD Audio (Atmos, TrueHD etc...)
> > 
> > Both dkore and PTer match the criteria, the quality is at least tier 3 (PTer possibly tier 2, haven't compared) and release naming is properly done. Both groups are active, have more releases than groups currently in the tiers, and release movies no other group has done.
> > There are currently 10 release groups in the tiers, of which a few seem highly inactive if not entirely dead. These groups do not keep up with film releases, so groups that match the current criteria should be added.
> 
> A bunch of those inactive rlsgrps are rlsgrp that used to be very active and had a high standard in the time they did active releases. And also had several so called GP releases. And over the time they could get lower in the tier list if we think it should happen
> 
So you agree PTer and dkore are more active, and from what I've found they have more releases.
> > The question is what reason there is to not add PTer and dkor
> 
> And this isn't how it works, if i ask you a question why i should add a rlsgrp I want a proper answer, and don't try to play the smart one..
So I'll give you another chance to answer the question in proper way.
>
…
I gave you my reasons, and you chose to ignore them, which means you have something against these groups or me. 

My reasons are in your comment, which I'm quoting in this comment, “So I'll give you another chance to answer”, or I'm closing the issue. Or save me the time if you won't answer, and close it yourself.

**Comment by TRaSH-** [comment]
little update: going to re-review dkor after some extra info from a team member that was willing to provide some extra info about that rlsgrp.

**Comment by FonduemangVI** [comment]
> little update: going to re-review dkor after some extra info from a team member that was willing to provide some extra info about that rlsgrp, being they could be helpful for a certain specific release profile.

Hey @TRaSH- where is this at? No rush FYI

**Comment by TRaSH-** [comment]
Let me take a look when I get home

**Comment by yammes08** [comment]
Agreement to add PTer but not the others.
