### ISSUE TITLE
[Request] Custom Format for qualities

### ISSUE THREAD

**Issue by ThibaultNocchi** [TRaSH-Guides/Guides#1619]
### For which application would like to see this Guide?

Radarr/Sonarr

### Describe what you would like to see in the Guide

When merging different qualities together, there's no custom format in the guide to differentiate between a resolution qualities.

For instance, my use case is that I made a "multi subs" custom format for animes with bundled multi subs and merged the 1080p qualities, cause I prefer the ease of having already fetched ass subtitles in french before the quality. But in that range, I'd like Sonarr to upgrade the quality if it finds a better source quality with multi subs.

Is it possible to have custom formats for Bluray/WEBDL/WEBRip/HDTV? If not, I'll just try my hand at it. :)

Thanks!

**Comment by TRaSH-** [comment]
If you merge them then the qualities are equal
If you don't want them to be equal then just don't merge them

**Comment by ThibaultNocchi** [comment]
Indeed, but I guess CF could be made so that qualities could be sorted even when merged. 
I can understand why that's not a priority though, thanks for your answer :)
