### ISSUE TITLE
[Bug] Recommended naming scheme for Radarr results in potentially undesirable filenames, due to bracket ordering.

### ISSUE THREAD

**Issue by jasonochs** [TRaSH-Guides/Guides#1684]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [ ] Sonarr
- [ ] Other

### Description

Note: I sent this to TRaSH on discord and he request that I submit an issue report for documentation.

On the Radarr recommended naming page: https://trash-guides.info/Radarr/Radarr-recommended-naming-scheme/

The recommendations have the VideoCodec in this format `[{VideoCodec}]`.

On the Sonarr recommended naming page: https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/

All of the formats have the VideoCodec in this format: `{[VideoCodec]}` (order of brackets are switched).

The Radarr order results in potentially having `...][]-RlsGrp.ext` in filenames, which I believe is unintended.

### Expected Behavior

The bracket order should be as it is on the Sonarr recommended naming page.

**Comment by nuxencs** [comment]
I'm pretty sure there is no such thing as no codec, but for consistency sake it does make sense to change this

**Comment by jasonochs** [comment]
> I'm pretty sure there is no such thing as no codec, but for consistency sake it does make sense to change this

Yeah, it happened to me and it turns out that it was because the torrents weren't complete (even after a recheck showed 100%). Once they completed (after removing and re-adding them to the torrent client, radarr scanned them and appropriately added the respective codecs. I don't think it would ever cause an issue under normal circumstances.
