### ISSUE TITLE
[Bug] Anime BD Tier 08 - Groups are not matched

### ISSUE THREAD

**Issue by RedDevilGiant** [TRaSH-Guides/Guides#1695]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [X] Sonarr
- [ ] Other

### Description

This Specifically pertains to the "Collection of Custom Formats" in the "Sonarr v4 Beta" guide

Groups are not matched to the groups listed in the custom format, therefore, files are not given the correct custom format score and Sonarr will incorrectly ignore them for acquiring 

Examples that I have seen are: "EMBER", "Judas"

![image](https://github.com/TRaSH-Guides/Guides/assets/29176867/2e816bf1-e01f-4f35-a4ee-28a99b0f7fe6)
![image](https://github.com/TRaSH-Guides/Guides/assets/29176867/20ebc31a-65af-4855-8679-30d7d6ec7e45)

### Expected Behavior

the expected behavior would be that a Group is matched to the group listed in the custom format, this will result in a particular custom format score.
this should result in Sonarr correctly deciding whether to acquire a file or not

Examples are (amongst others): "Subsplease", "VARYG"

![image](https://github.com/TRaSH-Guides/Guides/assets/29176867/be3965c9-ea3f-4c1d-bb47-5fa71daf6e8f)
![image](https://github.com/TRaSH-Guides/Guides/assets/29176867/06ea2ec4-21c8-433c-b142-e8b9944b5617)

### Additional Context

I've compared the RegEx pattern for EMBER and Judas with other groups in every list, there seem to be more that are formatted in the same way.

I've also checked the pattern on http://regexstorm.net/tester and found that the pattern for ex. EMBER does not result in a match, while the pattern for Subsplease does result in a match.

![image](https://github.com/TRaSH-Guides/Guides/assets/29176867/8539832b-8c86-47d5-b28f-70023f197128) ![image](https://github.com/TRaSH-Guides/Guides/assets/29176867/6b66e66f-e4a4-4120-8153-51207452d206)

I am no programmer and I barely understand this RegEx stuff so I could really use some expert help with this.

**Comment by FonduemangVI** [comment]
I can confirm that it is not matching on other Ember releases
![image](https://github.com/TRaSH-Guides/Guides/assets/15520607/e710a9a1-9d61-4ac3-8ba7-7403751ddb1d)

**Comment by FonduemangVI** [comment]
![image](https://github.com/TRaSH-Guides/Guides/assets/15520607/c2b3b9e4-2c98-4cbe-8acc-c7736c811c6d)

**Comment by FonduemangVI** [comment]
Can you post the full filename for the EMBER release please

**Comment by rg9400** [comment]
The issue is due to the fact that EMBER and Judas are in the BD Tiers. They will only match bluray releases and not web releases. We did not include them in web releases as we did not believe they deserved placement in any of the tiers to be honest.

**Comment by RedDevilGiant** [comment]
> Can you post the full filename for the EMBER release please

Original name: [EMBER] Tokyo Revengers S03E11 [1080p] [HEVC WEBRip] (Tokyo Revengers: Tenjiku-hen)
Original File name: [EMBER] Tokyo Revengers S3 - 11.mkv
Current filename: Tokyo Revengers (2021) - S03E11 - 048 - Nothing is left [WEBRip-1080p][10bit][x265][AAC 2.0][JA]-EMBER.mkv
![image](https://github.com/TRaSH-Guides/Guides/assets/29176867/52c95483-1cb7-4250-be09-2c93e20a4076)

> The issue is due to the fact that EMBER and Judas are in the BD Tiers.

ah, so if I understand correctly, the Regular expression matches them correctly but they aren't matched to the correct Tier.

> They will only match bluray releases and not web releases. 

Okay, so how can I Index them when they do release a web release?
Can I make a 7th Web Tier that contains them and give that a lower score than Web tier 6 (or maybe match the score to BD tier 08)?
does it generate conflicts if they are in multiple tiers?

>We did not include them in web releases as we did not believe they deserved placement in any of the tiers to be honest.

Is their quality that bad?
I wouln't call myself an Anime Connoisseur but I didn't notice any major issues with their releases
also AniDB doesn't think that they are that bad: https://anidb.net/anime/17969

**Comment by FonduemangVI** [comment]
> The issue is due to the fact that EMBER and Judas are in the BD Tiers. They will only match bluray releases and not web releases. We did not include them in web releases as we did not believe they deserved placement in any of the tiers to be honest.

Ah thanks RG I totally glossed over that fact
