### ISSUE TITLE
[Bug] Wrong dependency (exclusions) between Audio Custom Formats

### ISSUE THREAD

**Issue by rubasace** [TRaSH-Guides/Guides#1730]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [X] Sonarr
- [ ] Other

### Description

Audio Custom Formats (DTS, TrueHD, Atmos,  etc.) are configured in a way that they are mutually exclusive. For example, DTS audio has to be DTS and not Atmos. In the same way, Atmos has to be Atmos and not DTS.  

This causes issues when Radarr/Sonarr detect, for example, both DTS and True HD Atmos, as it doesn't add any score given that no Custom Format qualifies.

This issue happens for scene releases that sometimes show both DTS and TrueHD Atmos on the filename as well as when  Radarr (and not sure if Sonarr) detects TrueHD after scanning but DTS was indicated on the release name. [See Radarr issue](https://github.com/Radarr/Radarr/issues/9542)

### Expected Behavior

I believe the "not X" clauses should only be applied from "below", to avoid qualifying when another with a higher score is detected. For example:

- TrueHD ATMOS: only check for TrueHD + Atmos
- DTS X: check DTS X and not TrueHD ATMOS
- ATMOS (undefined): check for ATMOS and not DTS X or TrueHD

That way, when files present both DTS and TrueHD ATMOS (or any other combination) only the higher score matches.

I believe this is a reasonable assumption as a release with both DTS and TrueHD ATMOS should be treated as a TrueHD ATMOS release, because it has an audio track with such format.

**Comment by bakerboy448** [comment]
The excludes are intentional to avoid double scoring and multiple matches.

Changing the custom formats to support poorly named releases that lie about the audio format is highly unlikely.

**Comment by bakerboy448** [comment]
Ref https://github.com/Sonarr/Sonarr/issues/5598

Ref https://github.com/Sonarr/Sonarr/pull/5575

**Comment by glassbase** [comment]
My download was `Top.Gun.1986.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ` with TrueHD Atmos being the primary audio in the file.

Trash Guides use of "NOT" caused it to not apply at CF because it has both audio codecs

**Comment by bakerboy448** [comment]
`SWTYBLZ` is on the LQ list and would never ever be grabbed if you actually follow the guide.

Will defer to the team prior to closure, but no plans to change custom formats to facilitate a garbage shit group's non-standard garbage naming.

**Comment by yammes08** [comment]
I don't think the assumptions above are reasonable ones to make:
- The studio will decide for any single release which format the audio track will have. As DTS and Dolby are competitors, any release featuring HD tracks from both (and that are supposedly from the same studio master) therefore has to contain at least one audio track that has been manufactured by the release group. We have no way of knowing which track is genuine, or which methods were used to generate the second audio track.
- The proposed scoring logic only stands up on the basis that the more highly scored audio format is consistently set to be the file's primary audio track. If not, then - using the example above - the grab would be scored as per TrueHD Atmos, and then re-scored on disk as DTS-HD MA. This would cause a download loop.

More broadly, the guides are designed to automate the process of optimising grabs as much as possible. This relies on release groups adhering to well-recognised release and file naming conventions. The example release above does not adhere to these conventions, and the lack of adherence reveals the non-authenticity of the content therein.

I don't feel we should adopt this change.

**Comment by TRaSH-** [comment]
When we started to set up the CF, we primarily looked at existing original disk formats, considering the audio formats, such as Dolby and DTS. In general, you will not find them on the same original disk.

After extensive research on what proper release groups do or use, we decided to follow the rules they use, rather than the release groups that unnecessarily bloat the releases.

Additionally, it is problematic to establish a proper scoring system for a release if we allow double scoring, as in this case. This could potentially cause a loop, because after renaming the Starr apps, they will only recognize one set of the audio formats and not two. This would result in a loop.

To prevent this, the CF is set up in a way that prevents double scoring. This also means that release groups that bloat releases are given lower scores. In some cases, we also place them in the LQ for specific reasons.

**Comment by rubasace** [comment]
> You could easily solve your issue if you followed the guides on "How to set up Quality Profiles," and you wouldn't run into this issue in the first place.

@TRaSH- The above statement is simply not true. I've followed the guides but I'm Spanish and my parents only consume dubbed content (sadly, quite common in Spain).  I only consume content in original version. All major Spanish private trackers provide all their content in Dual (Spanish + English audio + original audio if it's not English). I have all relevant CFs from Trash Guides enabled on my apps as well as a `Dual` one that prioritizes the Dual tracks over any other CF.

It's from these private Spanish trackers that these release names come from and this is something I cannot simply "ban" via CFs or I'd miss the content I want.

If this is something that you don't want to support that is alright. I'll manage it locally and I'll try to script it in a way that I can still stay up to date with your updates.

> To prevent this, the CF is set up in a way that prevents double scoring. This also means that release groups that bloat releases are given lower scores. In some cases, we also place them in the LQ for specific reasons.

BTW, this is technically not correct. Mutually excluding from both CFs has the exact same effect as only excluding from the lower scored one: as long as DTS is DTS and not True HD ATMOS, True HD ATMOS can be just checking for itself.  Then you run into the following possible scenarios:

1. TrueHD ATMOS + DTS in the name: Only TrueHD ATMOS score is applied
2. TrueHD ATMOS in the name: TrueHD ATMOS score is applied
3. DTS in the name: DTS score is applied
4. Nothing in the name: no score is applied

I understand the edge case is in people wanting to provide custom scores that alter the priorities. For example, giving a higher score to DTS than to TrueHD ATMOS but, in that case, why would they even use the CF for the latter?

**Comment by bakerboy448** [comment]
> BTW, this is technically not correct. Mutually excluding from both CFs has the exact same effect as only excluding from the lower scored one: as long as DTS is DTS and not True HD ATMOS, True HD ATMOS can be just checking for itself. 

You missed the point.

The grabs will score both audios. The imports and on disk will only ever have the first audio track.
Thus you will have an endless grab loop.

**Comment by rubasace** [comment]
@bakerboy448 I'm sorry but that's not the case. First of all, this is my current local configuration and it works fine, so I know for a fact it doesn't score twice. Reason why is because I keep the "not" clauses on the lower CFs in reference to the higher ones. So it will only give the DTS score when it is DTS and IT'S NOT TRUEHD ATMOS. For releases with both in the name it will only give the TrueHD ATMOS score which in my opinion is the correct behaviour. With the current ones on the guides it doesn't score for any of the CFs, treating the release with the same score as one without any relevant audio format.

Again, I have this in place for both Sonarr and Radarr and the ones with both DTS and TrueHD ATMOS are only getting the TrueHD ATMOS. Tested with 7 different releases both on the parser and grabbing the movies in Radarr. With the guides CFs no score is added

**Comment by yammes08** [comment]
> @bakerboy448 I'm sorry but that's not the case. First of all, this is my current local configuration and it works fine, so I know for a fact it doesn't score twice. Reason why is because I keep the "not" clauses on the lower CFs in reference to the higher ones. So it will only give the DTS score when it is DTS and IT'S NOT TRUEHD ATMOS. For releases with both in the name it will only give the TrueHD ATMOS score which in my opinion is the correct behaviour. With the current ones on the guides it doesn't score for any of the CFs, treating the release with the same score as one without any relevant audio format.
> 
> 
> 
> Again, I have this in place for both Sonarr and Radarr and the ones with both DTS and TrueHD ATMOS are only getting the TrueHD ATMOS. Tested with 7 different releases both on the parser and grabbing the movies in Radarr. With the guides CFs no score is added

Take a look at my post further up - for all the examples you describe, is the "better" (higher scoring) audio track always set as the primary audio track? Can you confirm this?

In fairness to the team, when you were asked to provide an example release, you provided one which doesn't now seem to relate to your primary scenario which you've described in a later post (multiple audio Spanish releases?).

Also, there seems to be some confusion regarding "DTS". Across this discussion we've had "DTS", "DTS-HD MA" and "DTS:X" mentioned so far. Are you identifying several releases that have TrueHD Atmos plus one of the above?

Overall, I'm a touch confused.

I think I what we'd need to see next are multiple example release names that cover *all* the scenarios you're describing, as well as confirmation as to which of those audio tracks are set as the primary audio track in the file. If you can give us this detail then that will help.
