### ISSUE TITLE
[Bug] Synology Login Command

### ISSUE THREAD

**Issue by niyazaki** [TRaSH-Guides/Guides#1750]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [X] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [ ] Radarr
- [ ] Sonarr
- [ ] Other

### Description

On the SSH configuration part for Synology (https://trash-guides.info/Hardlinks/How-to-setup-for/Synology/#ssh) it says to connect to the "docker" user in order to get the uid and gid. But doing so leads to this error when inserting the (correct) password : Permission denied, please try again.

Workaround : connect to admin user using ssh and use id docker to get the "docker" user's ids.

I tried to sudo su - docker to switch user once connected to my admin user but this gives me this error:
su: warning: cannot change directory to /var/services/homes/docker: Permission denied
su: failed to execute /sbin/nologin: No such file or directory

After granting access to /homes (which is not what is stated in the step by step tutorial) the first error disapears but not the second one. I tried to give access to application and other settings in the same fashion but couldn't find a way to connect as the "docker" user.

### Expected Behavior

being able to connect as "docker" user

**Comment by bakerboy448** [comment]
Invalid. Not a bug

> it says to connect to the "docker" user in order to get the uid and gid

it does not say any such thing 

> Enter the login information of a Synology user account that has admin priveliges, as only members of the 'administrators' user group are able to use SSH.

[...]

> Once logged in type id $user. Change $user to the newly created username docker.
l

**Comment by niyazaki** [comment]
Yes you're right, I must have skipped a row or didn't pay enough attention. Happy to see that this was indeed correct :).
