### ISSUE TITLE
[Suggestion]  Add TeeWee to Dubs Only group

### ISSUE THREAD

**Issue by codefaux** [TRaSH-Guides/Guides#1763]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [X] Sonarr
- [ ] Other

### Description

Release group TeeWee recently appeared a LOT in my history, mostly with Azerbaijan or Mongolian Dubbed versions of releases (Fargo, Echo, some others)

### Expected Behavior

Well I don't think most people want them to download, lol

**Comment by TRaSH-** [comment]
![image](https://github.com/TRaSH-Guides/Guides/assets/6155095/b4f51d2a-1233-495a-92ee-fd34f0dc9b4d)

**Comment by codefaux** [comment]
I filed as 'bug/error' not 'request a guide' so the image is irrelevant but I get the point -- and I don't do Discord so I guess I'll just leave it at that.
