### ISSUE TITLE
[Bug] (Radarr/Sonarr): Add Preferred Quality Sizes

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-Guides/Guides#1831]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [X] Sonarr
- [ ] Other

### Description

Currently the json has preferred sizes but the guide does not

### Expected Behavior

Guide should have preferred sizes

**Comment by TRaSH-** [comment]
It's actually covered in the guide, and the json needs it so it can be set for the sync tools

![image](https://github.com/TRaSH-Guides/Guides/assets/6155095/81fc7431-a183-4dae-87d2-c7b037bcbc7e)

**Comment by bakerboy448** [comment]
May as well just give them that "high as possible" setting, no?

**Comment by TRaSH-** [comment]
the reason why i didn't add it to the table here, and did it written. is because there was a short time that there was difference between radarr/sonarr how it was handled or nightly/dev/stable version not sure any more
where the one had as max preferred one below where the other had five below.
