### ISSUE TITLE
[Request] Guide for Deluge or QBitTorrent clients/dockers to use Wireguard.

### ISSUE THREAD

**Issue by olejka2k** [TRaSH-Guides/Guides#1844]
### For which application would like to see this Guide?

qBittorrent

### Describe what you would like to see in the Guide

I am following the guide step by step, but I see that it is missing the step where you should point qbittorrent docker to use wireguard tunnel. I've signed up for TorGuard and successfully set everything up. 
Now this part of the guide : https://trash-guides.info/Misc/How-to-setup-Torguard-for-port-forwarding/
and this step specifically : "Rename the file from *.conf to wg0.conf and copy it to your wireguard folder of your VPN torrent client."
is not clear for me. I've put the file in, but the port cannot be checked by the client and the Ip address is not showing.
Thank you.

**Comment by bakerboy448** [comment]
GitHub is not for support questions. Please visit discord.
