### ISSUE TITLE
[Bug] GalaxyRG265 not included in LQ cf

### ISSUE THREAD

**Issue by rothnd** [TRaSH-Guides/Guides#1851]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [ ] Sonarr
- [ ] Other

### Description

GalaxyRG is included in LQ cf. I would like to request addition of GalaxyRG265 that keeps popping up as well please. 

### Expected Behavior

GalaxyRG265 are grabbed from public indexers.

**Comment by TRaSH-** [comment]
As discussed on discord, it's for now a none issue because it would be picked up by the so called golden rule CF.
