### ISSUE TITLE
Getting an error when the replace runs. 

### ISSUE THREAD

**Issue by bsmith76s** [TRaSH-Guides/Guides#1882]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [X] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [ ] Radarr
- [ ] Sonarr
- [ ] Other

### Description

Getting an error when the replace_for.py 
Things are still working but this error comes up after download.
here is a screen shot

### Expected Behavior

replace_for.py usually runs with no errors

### Screenshots

<img width="1345" alt="Screenshot 2024-04-14 at 6 31 28 PM" src="https://github.com/TRaSH-Guides/Guides/assets/69703764/b00b9f7f-b39c-418a-8809-5e0684ae863d">

### Additional Context

version  4.2.3
-- | --

_No response_

**Comment by bakerboy448** [comment]
GitHub is not for support; please check your sab logs for details.

trash discord or better yet the sabnzbd discord for support
