### ISSUE TITLE
[Bug] (Starr): DD+ and DD+ Atmos both matching on title with dual audio

### ISSUE THREAD

**Issue by EdLaughton** [TRaSH-Guides/Guides#1883]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [ ] Sonarr
- [ ] Other

### Description

A name such as "FilmX.2024.2160p.WEB-DL.DV.HDR.[Hindi.DDP5.1+English.DDPA5.1].H.265-FLUX" will satisfy both DD+ and DD+ Atmos custom formats leading to an inflated score.

<img width="1078" alt="Screenshot 2024-04-15 at 18 48 56" src="https://github.com/TRaSH-Guides/Guides/assets/49680999/765bd370-75fb-4743-8b53-8e4377d01797">

### Expected Behavior

It should only satisfy the DD+ Atmos custom format as this is the highest quality audio.

**Comment by glennos** [comment]
Ran into the same issue, I believe the fix is as simple as adding the following to the DD+ CFS (negate/required) `\b(ATMOS|DDPA)(\b|\d)`
