### ISSUE TITLE
[Bug] make the regex case incensitive with the (?i) modifier

### ISSUE THREAD

**Issue by remisharrock** [TRaSH-Guides/Guides#1964]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [X] Sonarr
- [ ] Other

### Description

regex do not catch case sensitive words sometimes. For example: H 265  is not captured fox the x265 regex because H is uppercase. 

### Expected Behavior

we should catch words in a case insensitive manner by adding the (?i)  at the begining of regex. 

### Additional Context

I have added a pull request for one example: https://github.com/TRaSH-Guides/Guides/pull/1963

**Comment by bakerboy448** [comment]
Invalid bug report
- invalid bug title
- no release names as examples

Not a bug and will never be accepted as a bug: Custom formats are case insensitive. Starr Ui and Starr docs are clear on this.

please utilize discord for support

**Comment by remisharrock** [comment]
My bad sorry, Indeed. I just figured that my problem was for 2160p that are negated ! Sorry I was messed up 😛
