### ISSUE TITLE
qBitTorrent File Alert Error on QNAP: No space left on device 

### ISSUE THREAD

**Issue by TheKaizenKing** [TRaSH-Guides/Guides#1966]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [X] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [ ] Radarr
- [ ] Sonarr
- [ ] Other

### Description

I'm playing around with the *arr stack on my QNAP TS-464eU, learning a little around containerisation and just generally playing around, but I've encountered an issue and reached the limits of my ability.

When I make a request through Radarr it contacts an indexer which finds the file and inputs it successfully into qBitTorrent - but this is when the issue starts. The file will hit 0.2% and display an error status and the system will run like a bag of hammers.

If you go to File Station it's bare, with no volumes visible and displays the following message:

"No volume has been created. To use this feature, go to [Storage & Snapshops] to create a volume first."

... because of this the error within qBitTorrent is "No space left on device".

If you restart the qnap device it will produce a RAMDisk error upon first starting up: "insufficient system storage: RAMDisk(/ or /tmp)"

Once the torrent has been removed from qBitTorrent everything returns back to normal operation.

I'd guess its some kind of permissions issue of the qBitTorrent application given it's trying to store something on another volume? Could anyone make any suggestions to help me overcome this issue?

**Hardware**

Device: TS-464eU
Firmware Version: QTS 5.2.0.2782
CPU: Intel Celeron N5095
Memory: 8GB

**Volumes**

System (Static SSD) : Primarily for storing applications

- Container station
-- Radarr
-- Prowlarr
-qBitTorrent (standalone application - qnap.org 

Media (Static HDD) : Download / Landing, Management and Storage of media

- Library (Shared folder) - Lock File (Oplocks) unchecked
-- Torrents
--- Movies
-- Usenet
--- Movies
-- Media
--- Movies

**qBitTorrent (App QNAP Club - myqnap.org)**

https://www.myqnap.org/product/qbittorrent-libtorrent-2-0-10/
Default save path: /Library/Torrents
Requests from Radarr attaches 'radarr' category and tells the download client to save to: /Library/Torrents/Movies

**Radarr (Container Station - Docker)**

Library folder is mounted to the container

Remote mapping:

Remote Path: /Library/Torrents/Movies
Local Path: /mnt/Torrents/Movies

### Expected Behavior

Instead of error-ing describing that there's no disk space the download client would pre-allocate the a portion of the ~14TB of free space and download the file successfully.

**Comment by nuxencs** [comment]
please give the issue a proper name

**Comment by TheKaizenKing** [comment]
> please give the issue a proper name

Sorry totally missed that. Updated thank you

**Comment by yammes08** [comment]
@TheKaizenKing - what issue with the Trash guides are you looking to have resolved?

**Comment by TheKaizenKing** [comment]
> @TheKaizenKing - what issue with the Trash guides are you looking to have resolved?

I don't think there is anything wrong specifically with the guide but perhaps has some missing info that could help me or other's that have faced this issue may have some wisdom. Having followed the guide meticulously and experimenting with various options related to the config or qBitTorrent I'm facing the issue described as above, which I can only assume is related to config or perhaps something related to QNAP (the latter of which is perhaps outside of the jurisdiction of this guide)?

**Comment by bakerboy448** [comment]
Not a guide issue. Open a support post on discord or better yet visit your NAS's support methods as this is unique and specific to your NAS and it's OS
