### ISSUE TITLE
[Bug] Issue with Notifiarr Sonarr naming sync

### ISSUE THREAD

**Issue by PH1L900D** [TRaSH-Guides/Guides#2016]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [X] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [ ] Radarr
- [ ] Sonarr
- [ ] Other

### Description

Sync naming from Notifiarr to Sonarr not working. When trying to update naming on Notifiarr website I see the following errors. I've also tried to update from the client side. Errors from client logs below.
![image](https://github.com/user-attachments/assets/055da0fe-b082-4fec-a5ee-c85fc33c5336)

### Expected Behavior

Naming updated as requested

### Screenshots

`465[ERROR] 2024/07/17 01:08:18 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
466NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
467[ERROR] 2024/07/17 01:08:19 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
468NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
469[ERROR] 2024/07/17 01:08:20 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
470NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
471[ERROR] 2024/07/17 01:08:20 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
472NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
473[ERROR] 2024/07/17 01:08:21 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
474NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
475[INFO] 2024/07/17 01:09:45 [gui requested] Event Triggered: Starting Sonarr profile and format sync.
476[INFO] 2024/07/17 01:09:45 [gui requested] Synced profiles and formats for Sonarr instance 1 (/http://192.168.0.6:8989)
477[INFO] 2024/07/17 01:09:46 [gui requested] Sent 120.3 KiB (742ms, buf=0/1024): Sonarr profiles and formats sync (elapsed: 12ms) => Website took 0s and replied with (313 B): success, "TRaSH Guides Sync payload processed. Worker: worker.1090780, Queue pos: 2" 
478[ERROR] 2024/07/17 01:09:47 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
479NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
480[ERROR] 2024/07/17 01:09:48 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
481NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
482[ERROR] 2024/07/17 01:09:50 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
483NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
484[ERROR] 2024/07/17 01:09:51 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
485NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
486[ERROR] 2024/07/17 01:09:51 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
487NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
488[INFO] 2024/07/17 01:11:25 [api requested] Event Triggered: Starting Sonarr profile and format sync.
489[INFO] 2024/07/17 01:11:25 [api requested] Synced profiles and formats for Sonarr instance 1 (/http://192.168.0.6:8989)
490[INFO] 2024/07/17 01:11:26 [api requested] Sent 120.3 KiB (663ms, buf=0/1024): Sonarr profiles and formats sync (elapsed: 11ms) => Website took 1s and replied with (313 B): success, "TRaSH Guides Sync payload processed. Worker: worker.1090781, Queue pos: 2" 
491[ERROR] 2024/07/17 01:11:27 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
492NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
493[ERROR] 2024/07/17 01:11:28 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
494NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
495[ERROR] 2024/07/17 01:11:30 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
496NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
497[ERROR] 2024/07/17 01:11:31 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
498NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat
499[ERROR] 2024/07/17 01:11:32 Request failed. Status: 409: Conflict, Message: updating naming: invalid status code, 409 >= 300, constraint failed
500NOT NULL constraint failed: NamingConfig.CustomColonReplacementFormat`

### Additional Context

All other Sonarr syncs work as expected.

**Comment by bakerboy448** [comment]
TRaSH guides has no relation to Notifiarr's Patron Feature of TRaSH Sync.  Visit Notifiarr's Discord for support with Notifiarr
