### ISSUE TITLE
[Request] add trashs id for original language only to be used in the 3rd party apps

### ISSUE THREAD

**Issue by salvo-github** [TRaSH-Guides/Guides#2084]
Which application would you like to see this Guide for?
Radarr / Sonarr

Description of Desired Guide Content
I'm trying to configure Recyclarr to add a custom format (CF) for both Sonarr and Radarr, aiming to prioritize media in the original language. Currently, the custom format for the original language has the following trash ID: "trash_id": "guide-only". Unfortunately, this ID isn't supported by Recyclarr, and during sync, the score gets reset to 0 instead of being set to -10000.

I would like to request an additional custom format for Radarr and Sonarr, each with a properly supported trash ID that can be used in Recyclarr’s config and assigned to a quality profile.

If there's a process or guidelines for generating trash IDs, I'd be happy to submit a change request myself. Could you please provide any instructions on this process?

**Comment by ciotorcristian** [comment]
I would highly appreciate if you could add IDs at least for Original Language.

**Comment by AlejandroAkbal** [comment]
Yes please, add an 'Original language' trash id, with fallback to something we can configure

If a trash id is not possible, please create a guide, because I think its what most users would want to have

**Comment by TRaSH-** [comment]
> If a trash id is not possible, please create a guide, because I think its what most users would want to have

https://trash-guides.info/Sonarr/Tips/How-to-setup-language-custom-formats/

There is already a guide for it

**Comment by AlejandroAkbal** [comment]
> > If a trash id is not possible, please create a guide, because I think its what most users would want to have
> 
> https://trash-guides.info/Sonarr/Tips/How-to-setup-language-custom-formats/
> 
> There is already a guide for it

I meant a guide to configure using recyclarr config

**Comment by TRaSH-** [comment]
> > > If a trash id is not possible, please create a guide, because I think its what most users would want to have
> > 
> > 
> > https://trash-guides.info/Sonarr/Tips/How-to-setup-language-custom-formats/
> > There is already a guide for it
> 
> I meant a guide to configure using recyclarr config

They have a own wiki that covers that, and in the guide discord, recyclarr has a dedicated support channel where you can ask recyclarr specific questions. 
This isn't the place to ask support questions or request a guide

**Comment by grunwalski** [comment]
I might be at the wrong place, but maybe I am not. Lets see:

As far as I understood the guides, at the moment there is no guide that achieves the following:

- I speak two languages. English and my native language.
- I want everything with english asa original language, in its original language.
- if original language is not english, i want my native language
- ideally choose always dual/multi with original language==english and my native language
- but NEVER choose just my native language, if original language is english

Am I wrong and this guide exist and I just didnt understood it?
Or maybe, thats a limitation by Sonarr/Radarr?


btw: GREAT WORK. Thanks for your guides, they helped me a lot!

**Comment by bakerboy448** [comment]
https://trash-guides.info/Sonarr/Tips/How-to-setup-language-custom-formats/#language-prefer-x-but-ill-take-y

That is more of a support request than a guide feature request please visit discord for support; github is not for support.

**Comment by chunkyfen** [comment]
Litte update but using sync with this in my config file:
    custom_formats:
      # Language: Not Original
      - trash_ids:
          - d6e9318c875905d6cfb5bee961afcea9  # Trash ID for Language: Not Original
        assign_scores_to:
          - name: HD Bluray + WEB
            score: -10000  # Set the score to -10000
Sync my radarr with the CF at -10000

So I guess this is resolved?

**Comment by AlejandroAkbal** [comment]
> - trash_ids:
>       - d6e9318c875905d6cfb5bee961afcea9  # Trash ID for Language: Not Original
>     assign_scores_to:
>       - name: HD Bluray + WEB
>         score: -10000  # Set the score to -10000

Nice! 
How / Where did you find that ID?

Is there another one for sonarr?

**Comment by chunkyfen** [comment]
> > * trash_ids:
> >   - d6e9318c875905d6cfb5bee961afcea9  # Trash ID for Language: Not Original
> >   assign_scores_to:
> >   - name: HD Bluray + WEB
> >   score: -10000  # Set the score to -10000
> 
> Nice! How / Where did you find that ID?
> 
> Is there another one for sonarr?

Here: https://trash-guides.info/Radarr/Tips/How-to-setup-language-custom-formats/

I don't know, you'd have to check the sonarr page but I don't see why it couldn't just work for sonarr

**Comment by AlejandroAkbal** [comment]
> > > * trash_ids:
> > >   
> > >   * d6e9318c875905d6cfb5bee961afcea9  # Trash ID for Language: Not Original
> > >     assign_scores_to:
> > >   * name: HD Bluray + WEB
> > >     score: -10000  # Set the score to -10000
> > 
> > 
> > Nice! How / Where did you find that ID?
> > Is there another one for sonarr?
> 
> Here: [trash-guides.info/Radarr/Tips/How-to-setup-language-custom-formats](https://trash-guides.info/Radarr/Tips/How-to-setup-language-custom-formats/)
> 
> I don't know, you'd have to check the sonarr page but I don't see why it couldn't just work for sonarr

Where? Do I have to do something special?
![image](https://github.com/user-attachments/assets/ee595de9-64f8-4882-96bd-84f6ba8b5e3a)

**Comment by chunkyfen** [comment]
> > * trash_ids:
> >   - d6e9318c875905d6cfb5bee961afcea9  # Trash ID for Language: Not Original
> >   assign_scores_to:
> >   - name: HD Bluray + WEB
> >   score: -10000  # Set the score to -10000
> 
> Nice! How / Where did you find that ID?
> 
> Is there another one for sonarr?

I feel like this website is gaslighting me, I copied the id from there and now it's gone. I'll have to go thru my history later. The id does work so Idk 😐

**Comment by bakerboy448** [comment]
GitHub is not for support.
Please use discord for support.

**Comment by TRaSH-** [comment]
This has been done with #2159 and is available for the 3rd party sync apps.
