### ISSUE TITLE
[Bug]Custom Format Matching Issue: HDR Format Not Detected When Title Contains "DV"

### ISSUE THREAD

**Issue by nosheen-g** [TRaSH-Guides/Guides#2161]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [ ] Radarr
- [X] Sonarr
- [ ] Other

### Description

When processing titles that contain "DV," Sonarr fails to correctly identify and account for "HDR" when calculating the custom format score. This behavior impacts the scoring of releases, as "HDR" is ignored if "DV" is present in the title.

Example:
Release:
Dexter Original Sin S01E01 And in the beginning 2160p PMTP WEB-DL DDP5 1 DV HDR H 265-FLUX
Expected custom format score: PMTP WEB Tier 01 HDR 3000
Actual custom format score: PMTP WEB Tier 01 2000

### Expected Behavior

Both "HDR" and "DV" should be detected and contribute to the custom format score, based on the defined scoring rules.

**Comment by bakerboy448** [comment]
Not a bug `DV HDR` is not `HDR` they are distinct custom formats and specifically designed to not overlap. The HDR custom formats group has formats designed so as to not be cherry-picked and shall be used in full.
